In [21]:
import pandas as pd

In [22]:
# Q1 
import pandas as pd

ROLL_NUMBER = "1024170453"  

fixed_entries = [
    {"question": "what is the annual fee", "answer": "The annual fee is Rs 500.",
     "keywords": "fee cost price charge", "category": "billing"},
    {"question": "how to reset password", "answer": "Go to Settings > Reset Password.",
     "keywords": "password reset login", "category": "account"},
    {"question": "what are your working hours", "answer": "We are open 9 AM to 5 PM.",
     "keywords": "hours timing open time", "category": "general"},
    {"question": "how can i pay the fee", "answer": "You can pay via UPI, card, or net banking.",
     "keywords": "pay payment upi fee", "category": "billing"},
]

categories = ["billing", "account", "general"]
last_two_digits = [int(d) for d in ROLL_NUMBER[-2:]]

personalized_entries = []

# Build entries based on each digit's category
custom_content = {
    "billing": {"question": "why was i charged twice this month",
                "answer": "Duplicate charges are usually refunded within 5-7 business days.",
                "keywords": "charge refund duplicate"},
    "account": {"question": "how do i update my registered mobile number",
                "answer": "Go to Profile > Edit Contact Details to update your mobile number.",
                "keywords": "mobile number update"},
    "general": {"question": "where is your office located",
                "answer": "Our office is located at the main campus building, Block A.",
                "keywords": "office location address"},
}

for digit in last_two_digits:
    cat = categories[digit % 3]
    entry = dict(custom_content[cat])
    entry["category"] = cat
    personalized_entries.append(entry)

df = pd.DataFrame(fixed_entries + personalized_entries)
df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,where is your office located,Our office is located at the main campus build...,office location address,general
5,why was i charged twice this month,Duplicate charges are usually refunded within ...,charge refund duplicate,billing

In [23]:
# Q2 
def score_query(query, df):
    query_words = set(query.lower().split())
    results = []
    for idx, row in df.iterrows():
        keyword_set = set(row["keywords"].lower().split())
        question_words = set(row["question"].lower().split())
        overlap = query_words & (keyword_set | question_words)
        score = len(overlap)
        if score > 0:
            results.append((row["question"], row["answer"], row["category"], score))
    results.sort(key=lambda x: x[3], reverse=True)
    return results


matches = score_query("how do i reset my password", df)
for m in matches:
    print(m)

('how to reset password', 'Go to Settings > Reset Password.', 'account', 3)
('how can i pay the fee', 'You can pay via UPI, card, or net banking.', 'billing', 2)
('why was i charged twice this month', 'Duplicate charges are usually refunded within 5-7 business days.', 'billing', 1)

In [24]:
# Q3 
def same_category(category_name, df):
    return df[df["category"] == category_name]


sample_category = personalized_entries[0]["category"]
print("Category used:", sample_category)
same_category(sample_category, df)

Category used: general

,question,answer,keywords,category
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
4,where is your office located,Our office is located at the main campus build...,office location address,general

In [25]:
# Q4 
entry_index = 0 
new_keyword = input("Enter a new keyword to add: ")

df.at[entry_index, "keywords"] = df.at[entry_index, "keywords"] + " " + new_keyword

filename = f"{ROLL_NUMBER}_faq_data.csv"
df.to_csv(filename, index=False)
print(f"Saved to {filename}")
df

Enter a new keyword to add:  apple

Saved to 1024170453_faq_data.csv

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge apple,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,where is your office located,Our office is located at the main campus build...,office location address,general
5,why was i charged twice this month,Duplicate charges are usually refunded within ...,charge refund duplicate,billing